FROM php:7.0-apache
MAINTAINER jose nazario <jose@monkey.org>
LABEL version="1.0" description="nosqli-labs Docker image"

# modifying from https://hub.docker.com/r/spittet/php-mongodb/

RUN apt-get update && apt-get install -y gnupg2
RUN pecl install mongodb
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN docker-php-ext-enable mongodb


COPY . /var/www/html
RUN  chown -R www-data:www-data *
RUN sed -i s/"localhost:27017"/"mongo:27017"/g /var/www/html/user_lookup.php && \
	sed -i s/"localhost:27017"/"mongo:27017"/g /var/www/html/populate_db.php && \
	sed -i s/"localhost:27017"/"mongo:27017"/g /var/www/html/guess_the_key.php
